service:
  sshd:
    enabled: true
    running: true
  nginx:
    enabled: true
    running: true
  isubata.python:
    enabled: true
    running: true
  isubata.golang:
    enabled: false
    running: false
  isubata.nodejs:
    enabled: false
    running: false
  isubata.perl:
    enabled: false
    running: false
  isubata.php:
    enabled: false
    running: false
  isubata.ruby:
    enabled: false
    running: false
  mysql:
    enabled: true
    running: true

