# -*- mode: Yaml; -*-
# vi: set ts=2 sw=2 sts=0 et:

---
- hosts: all
  user: ubuntu
  become: yes
  # for ansible_env
  gather_facts: yes

  roles:
    - common
    - bench
    - golang
#   - nodejs
#   - perl
#   - php
#   - python
#   - ruby
    - mysql
    - nginx
