# -*- mode: ruby -*-
# vi: set ft=ruby ts=2 sw=2 sts=0 et :
# ref.
#   https://github.com/matsuu/ansible-isucon
#   https://github.com/matsuu/vagrant-isucon

$disable_unattended_upgrades =<<-SCRIPT
echo "-- Disabling unattended upgrades --"
cat << EOF > /etc/apt/apt.conf.d/51disable-unattended-upgrades
APT::Periodic::Update-Package-Lists "0";
APT::Periodic::Unattended-Upgrade "0";
EOF
SCRIPT

$setup_basepkg =<<-SCRIPT
echo "-- Start base packages setup --"
export DEBIAN_FRONTEND="noninteractive"
apt-get -y update
apt-get -y install dselect
dselect update
dpkg --set-selections </tmp/sakura_ubuntu_package.list
apt-get -y dselect-upgrade
echo '-- Finish base packages setup --'
SCRIPT

$setup_quarifier_environment =<<-SCRIPT
set -e
echo "-- ISUCON7 quarifier setup --"
export DEBIAN_FRONTEND="noninteractive"
apt-get -y install python-pip
pip install ansible
(
  cd /tmp/ansible/
  PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ansible-playbook -i localhost, -c local /tmp/ansible/site.yml
)
echo '-- Finish quarifier setup --'
SCRIPT

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provider "virtualbox" do |vm|
    vm.name   = "isucon7-quarifier"
    vm.cpus   = 2
    vm.memory = 2048
  end
  config.vm.hostname = "isucon7-quarifier"

  config.vm.provision :shell, inline: $disable_unattended_upgrades
  config.vm.provision :file,  source: "../misc/sakura_ubuntu_package.list", destination: "/tmp/sakura_ubuntu_package.list"
  config.vm.provision :shell, inline: $setup_basepkg
  config.vm.provision :file,  source: "./roles/", destination: "/tmp/ansible/roles"
  config.vm.provision :file,  source: "./site.yml", destination: "/tmp/ansible/site.yml"
  config.vm.provision :shell, inline: $setup_quarifier_environment
end

