# -*- mode: ruby -*-
# vi: set ft=ruby :

$disable_unattended_upgrades =<<-SCRIPT
echo "-- Disabling unattended upgrades --"
cat << EOF > /etc/apt/apt.conf.d/51disable-unattended-upgrades
APT::Periodic::Update-Package-Lists "0";
APT::Periodic::Unattended-Upgrade "0";
EOF
SCRIPT

$setup_basepkg =<<-SCRIPT
echo "-- Start base packages setup --"
export DEBIAN_FRONTEND="noninteractive"
apt-get -y update
apt-get -y install dselect
dselect update
dpkg --set-selections </tmp/sakura_ubuntu_package.list
apt-get -y dselect-upgrade
echo '-- Finish base packages setup --'
SCRIPT

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provider "virtualbox" do |vm|
    vm.name = "packer-test"
    vm.customize ["modifyvm", :id, "--memory", "4096"]
  end

  config.vm.provision :shell, inline: "echo ubuntu:ubuntu | chpasswd"
  config.vm.provision :shell, inline: "echo \"ubuntu ALL=(ALL) NOPASSWD:ALL\" >/etc/sudoers.d/90-ubuntu-user"
  config.vm.provision :shell, inline: $disable_unattended_upgrades
  config.vm.provision :file,  source: "../sakura_ubuntu_package.list", destination: "/tmp/sakura_ubuntu_package.list"
  config.vm.provision :shell, inline: $setup_basepkg
end

